language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - android-23
  - build-tools-23.0.2
  - android-25
  - build-tools-25.0.0
  - android-27
  - build-tools-27.0.3
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - ./gradlew build
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'